
services:
  backend:
    image: sakamalao-backend:latest
#    build:
#      context: .. # remonte d'un niveau pour inclure sakamalo-api
#      dockerfile: docker/Dockerfile
    container_name: sakamalao-backend
    networks:
      - sakamalao-network
    expose:
      - "8081"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: sakamalao-db
    environment:
      POSTGRES_USER: sakamalao
      POSTGRES_PASSWORD: sakamalao
      POSTGRES_DB: sakamalao_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sakamalao-network
    restart: unless-stopped

volumes:
  db-data:

networks:
  sakamalao-network:
    external: true
