spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sakamalao_db
    username: sakamalao
    password: sakamalao
  jpa:
    hibernate:
      ddl-auto: update   # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: s4k4m4l40-s3cr37
    expiration: 360000